esphome:
    name: kueched1
    platform: ESP8266
    board: d1_mini
  
  # Enable logging
  logger:
  
  # Enable Home Assistant API
  api:
    password: ""
  ota:
    password: ""
  
  wifi:
    ssid: ""
    password: ""
  
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: "Kueched1 Fallback Hotspot"
      password: ""
  
  captive_portal:

      
    - platform: gpio
      pin: D3
      name: "Essenklingeld1"
      filters:
        - invert
      on_multi_click:
      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          - homeassistant.service:
             service: script.toggle
             data:
              entity_id: script.fake_alarm
          - logger.log: "double click - Fake Alarm"
      - timing:
        - ON for at most .49s
        - OFF for at least 0.25s
        then:
          - homeassistant.service:
             service: script.toggle
             data:
              entity_id: script.essensklingel
          - logger.log: "single click - Essensklingel"